"""empty message

Revision ID: 14ba6608b48d
Revises: ea3c57af3c16
Create Date: 2023-04-17 14:54:10.018397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ba6608b48d'
down_revision = 'ea3c57af3c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorite__planet')
    op.drop_table('favorite__vehicle')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'])
        batch_op.drop_column('vehicles')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('pilots')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pilots', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicles', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicle_id')

    op.create_table('favorite__vehicle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='favorite__vehicle_pkey')
    )
    op.create_table('favorite__planet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='favorite__planet_pkey')
    )
    op.drop_table('favorite_planet')
    # ### end Alembic commands ###
